version: "3.9"

services:

  api:
    build: ./
    image: werkstuk:latest
    ports:
      - "8000:${APIPORT}"
    environment:
     PG_CONNECTION_STRING: postgress://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5432/${POSTGRES_DB}
     PORT: 1234
    volumes:
     - ./api/src:/usr/app/src
    depends_on:
     - pg

  pg:
   container_name: ${POSTGRES_DB}
   image: postgres:latest
   ports:
    - 5432:5432
   environment:
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB
   volumes:
    - ./pgdata:/var/lib/postgresql/data