version: "3.9"

services:

  api:
    container_name: ${API_NAME}
    build: ./
    image: werkstuk:latest
    ports:
      - 8000:${APIPORT}
    environment:
     PG_CONNECTION_STRING: postgress://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DB}:${PORT}/${POSTGRES_DB}
     PORT: ${APIPORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
     - ./api/src:/usr/app/src
    depends_on:
     - pg

  pg:
   container_name: ${POSTGRES_DB}
   image: postgres:latest
   ports:
    - 5432:${PORT}
   environment:
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB
   volumes:
    - ./pgdata:/var/lib/postgresql/data