version: "3.9"

services:

  api:
    build: ./
    image: werkstuk:latest
    ports:
      - "8000:${PORT}"
    environment:
     - PG_CON=postgress://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5432/${POSTGRES_DB}
     - APIPORT
    volumes:
     - ./api/src:/usr/app/src
    depends_on:
     - pg

  pg:
   image: postgres:latest
   ports:
    - 5432:5432
   environment:
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB
    - POSTGRES_HOST
   volumes:
    - ./pgdata:/var/lib/postgresql/data